Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 120
  Exclude:
    - menu.rb

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - menu.rb

Metrics/CyclomaticComplexity:
  Max: 8    

Style/ClassVars:
  Exclude:
    - car.rb
    - route.rb
    - station.rb
    - train.rb

Layout/EndOfLine:
  Exclude:
    - main.rb
    - manufacturer.rb
